[package]
name = "emulator"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
log.workspace = true
serde.workspace = true
rmp-serde = "1"
structview = "1"
code = { path = "../code" }
